import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const monitor=fs.readFileSync(path.join(root,'src','monitor.mjs'),'utf8');
const scheduler=fs.readFileSync(path.join(root,'src','monitor-scheduler.mjs'),'utf8');
const server=fs.readFileSync(path.join(root,'src','server.mjs'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
assert.match(monitor,/AURA_MONITOR/);
assert.match(monitor,/name==='Tony'/);
assert.match(monitor,/a\?\.protected/);
assert.match(monitor,/a\?\.external/);
assert.match(monitor,/generateSteveReport/);
assert.match(monitor,/STEVE_EMAIL_ENABLED/);
assert.match(scheduler,/runHealthScan/);
assert.match(server,/\/api\/monitor\/scan/);
assert.match(server,/\/api\/monitor\/report/);
assert.match(app,/Phase 5 Aura \+ Steve Operations/);
console.log('Aura OS v0.5.0 Phase 5 monitoring tests passed. Tony remains excluded from automated health intervention.');
