import assert from 'node:assert/strict';
process.env.OUTBOUND_SMTP_HOST='smtp.example.com';
process.env.OUTBOUND_SMTP_PORT='465';
process.env.OUTBOUND_SMTP_USER='sender@example.com';
process.env.OUTBOUND_SMTP_PASSWORD='secret';
process.env.OUTBOUND_FROM_EMAIL='sender@example.com';
process.env.OUTBOUND_FROM_NAME='Ziya Energy';
process.env.OUTBOUND_ENABLED='true';
const {buildMessage,smtpReady}=await import('../src/mailer.mjs');
const {eligibleOutboundDrafts,outboundConfig}=await import('../src/outbound.mjs');
assert.equal(smtpReady(),true);
const msg=buildMessage({toEmail:'buyer@example.co.za',toName:'Thabo Molefe',subject:'Energy assessment for Example Manufacturing',body:'Hi Thabo,\n\nWould you be open to a brief conversation?',messageId:'<test@ziya.local>'});
assert.match(msg.raw,/From: Ziya Energy <sender@example.com>/);
assert.match(msg.raw,/To: Thabo Molefe <buyer@example.co.za>/);
assert.match(msg.raw,/If this is not relevant/i);
assert.equal(outboundConfig().enabledByConfig,true);
const lead={id:'l1',batchId:'b1',fridayStatus:'APPROVED',email:'buyer@example.co.za'};
const draft={id:'d1',leadId:'l1',batchId:'b1',status:'APPROVED',recipientEmail:'buyer@example.co.za'};
let db={leads:[lead],emailDrafts:[draft],outboundMessages:[],doNotContact:[]};
assert.deepEqual(eligibleOutboundDrafts(db).map(x=>x.id),['d1']);
db.outboundMessages.push({leadId:'l1',recipientEmail:'buyer@example.co.za',status:'SENT'});
assert.equal(eligibleOutboundDrafts(db).length,0,'A sent lead must never be queued again.');
db.outboundMessages=[];db.doNotContact=[{email:'buyer@example.co.za'}];
assert.equal(eligibleOutboundDrafts(db).length,0,'Do-not-contact email must never be queued.');
console.log('Aura OS v0.4.0 Phase 4 tests passed. Ultron-approved-only queue, duplicate-send lock, DNC guard and SMTP message construction enforced.');
