// Phase 5 Aura + Steve Operations preserved inside the v0.8.5 company operating system.
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let data={status:null,summary:null,opps:[],activities:[],sources:[],agents:[],config:{sources:[],stages:[]},leads:[],drafts:[]};let view='overview';let selected=null;
const fmtR=n=>Number(n||0)?`R${Math.round(Number(n)).toLocaleString('en-ZA')}`:'—';const fmt=n=>Number(n||0).toLocaleString('en-ZA');const when=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'})};
const stageLabel=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
async function j(url,opt){const r=await fetch(url,opt);const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||`HTTP ${r.status}`);return x}
async function load(){
  const [status,summary,opps,activities,sources,agents,config,leads,drafts]=await Promise.all([
    j('/api/status'),j('/api/crm/summary'),j('/api/crm/opportunities?limit=1000'),j('/api/crm/activities?limit=250'),j('/api/crm/source-performance'),j('/api/crm/agent-performance'),j('/api/crm/config'),j('/api/leads').catch(()=>[]),j('/api/drafts').catch(()=>[])
  ]);data={status,summary,opps,activities,sources,agents,config,leads,drafts};render();
}
function brand(){return `<div class="brand"><span class="mark"><i></i><i></i><i></i></span>ZIYA <small>&nbsp;ENERGY</small></div>`}
function nav(){const items=[['overview','Executive'],['pipeline','CRM Pipeline'],['leads','Lead Database'],['agents','Agents'],['outreach','Outreach'],['operations','Operations']];return `<div class="nav">${items.map(([k,l])=>`<button data-view="${k}" class="${view===k?'active':''}">${l}</button>`).join('')}</div>`}
function top(){const s=data.status||{},h=s.monitoring?.health||'UNKNOWN';return `<div class="topbar">${brand()}${nav()}<div class="top-status"><i class="dot ${h==='HEALTHY'?'good':'warn'}"></i>AURA ${h}</div></div>`}
function metric(label,value,sub=''){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function hero(){const c=data.status?.auraConversation||{};return `<section class="hero"><div class="hero-main"><div class="eyebrow">ZIYA ENERGY · COMPANY OPERATING SYSTEM</div><h1>Ziya CRM</h1><p>The single source of truth for leads, opportunities, agent activity, outreach, proposal progress and deal attribution.</p></div><div class="aura-brief"><div><div class="label">EXECUTIVE INTERFACE</div><h3>Aura</h3><p>Ask Aura about the pipeline, lead database, source performance, proposal status or any CRM record. When conversational voice is re-enabled, she uses this CRM as factual memory.</p></div><div><div class="query"><input id="auraQ" placeholder="Ask Aura: How many projects are in the pipeline?"><button id="askAura">Ask</button></div><div class="voice-state">${c.llmEnabled?'Conversational Aura available':'Conversational Aura dormant · CRM intelligence remains active'}</div></div></div></section>`}
function summaryMetrics(){const s=data.summary||{},q=data.status?.leadQuota||{},t=data.status?.research?.providers?.tavily||{};const used=q.global?.used||0,limit=q.global?.limit||180;const tav=t.usage?.usage??0,cap=t.monthlyCreditCap||900;return `<section class="metrics">${metric('Open Pipeline',fmt(s.open),'opportunities')}${metric('Qualified',fmt(s.qualified),'progressing')}${metric('Proposals',fmt(s.proposals),'ready or later')}${metric('Won',fmt(s.won),'closed clients')}${metric('Lead Database',fmt(s.companies),'unique companies')}${metric('Approved This Month',`${used}/${limit}`,'Vision · Peter · MJ')}${metric('Tavily Credits',`${tav}/${cap}`,t.budgetBlocked?'PAUSED':'monthly hard cap')}${metric('Waiting Info',fmt(s.waitingInformation),'opportunities')}${metric('Pipeline Value',fmtR(s.pipelineValue),'recorded values')}</section>`}
const lanes=['DISCOVERED','FRIDAY_REVIEW','APPROVED','OUTREACH','QUALIFYING','AWAITING_INFORMATION','TONY_PROCESSING','PROPOSAL_READY','OWNER_REVIEW','PROPOSAL_PRESENTED','NEGOTIATION','WON'];
function oppCard(o){return `<article class="opp" data-opp="${esc(o.id)}"><b>${esc(o.company?.name||o.title)}</b><small>${esc(o.company?.primaryAddress||o.site?.address||'Address not recorded')}</small><small>${o.estimatedKwhMin?`${fmt(o.estimatedKwhMin)}–${fmt(o.estimatedKwhMax)} kWh/month`:'Usage estimate not recorded'}</small><div class="source"><span>${esc(o.source||'Other')}</span><span>${o.estimatedValue?fmtR(o.estimatedValue):`Friday ${o.fridayScore??'—'}`}</span></div></article>`}
function kanban(){return `<div class="kanban">${lanes.map(st=>{const rows=data.opps.filter(o=>o.stage===st);return `<section class="lane"><div class="lane-head"><b>${stageLabel(st)}</b><span>${rows.length}</span></div>${rows.length?rows.slice(0,40).map(oppCard).join(''):'<div class="empty">No records</div>'}</section>`}).join('')}</div>`}
function sourcePanel(){const rows=data.sources.filter(x=>x.leads).sort((a,b)=>b.leads-a.leads);const max=Math.max(1,...rows.map(x=>x.leads));return `<section class="panel"><div class="panel-head"><h3>Lead Sources</h3><span>CRM ATTRIBUTION</span></div><div class="source-bars">${rows.length?rows.map(x=>`<div class="source-row"><b>${esc(x.source)}</b><div class="bar"><i style="width:${Math.round(x.leads/max*100)}%"></i></div><span>${x.leads}</span></div>`).join(''):'<div class="empty">Source data will appear as agents publish leads.</div>'}</div></section>`}
function activityPanel(limit=12){return `<section class="panel"><div class="panel-head"><h3>Company Activity</h3><span>IMMUTABLE CRM TIMELINE</span></div><div class="activity">${data.activities.slice(0,limit).map(a=>`<div class="activity-item"><time>${esc(when(a.createdAt))}</time><div><b>${esc(a.actor)} · ${esc(stageLabel(a.type))}</b><p>${esc(a.summary)}</p></div></div>`).join('')||'<div class="empty">No CRM activity yet.</div>'}</div></section>`}
function overview(){const s=data.status||{},crm=data.summary||{};return `${hero()}${summaryMetrics()}<div class="section-head"><div><div class="label">EXECUTIVE VIEW</div><h2>State of the business</h2></div><p>Operational data is generated by agents and consolidated into one CRM record per company and opportunity.</p></div><div class="grid-2">${sourcePanel()}${activityPanel(9)}</div><div class="section-head"><div><div class="label">PIPELINE</div><h2>Current opportunities</h2></div><p>${crm.open||0} open opportunities across the Ziya sales process.</p></div>${kanban()}<div class="section-head"><div><div class="label">SYSTEM</div><h2>Infrastructure</h2></div></div><div class="grid-3"><section class="panel rows"><div class="panel-head"><h3>Aura OS</h3><span>PRODUCTION</span></div><div class="row"><span>Health</span><b>${esc(s.monitoring?.health||'—')}</b></div><div class="row"><span>Open incidents</span><b>${s.monitoring?.openCount||0}</b></div><div class="row"><span>Lead cycle</span><b>${s.leadCycle?.enabled?'ACTIVE':'STOPPED'}</b></div></section><section class="panel rows"><div class="panel-head"><h3>Tony</h3><span>PROTECTED OBSERVER</span></div><div class="row"><span>Status</span><b>${esc(s.tonyObserver?.status||'—')}</b></div><div class="row"><span>Completed PDFs</span><b>${s.tonyObserver?.completed?.total||0}</b></div><div class="row"><span>CRM access</span><b>NONE</b></div></section><section class="panel rows"><div class="panel-head"><h3>CRM Sync</h3><span>AUTOMATIC</span></div><div class="row"><span>Companies</span><b>${crm.companies||0}</b></div><div class="row"><span>Opportunities</span><b>${crm.opportunities||0}</b></div><div class="row"><span>Last sync</span><b>${esc(crm.lastSyncAt?new Date(crm.lastSyncAt).toLocaleTimeString():'—')}</b></div></section></div>`}
function pipeline(){return `<div class="section-head"><div><div class="label">CRM PIPELINE</div><h2>Opportunity flow</h2></div><p>Click any opportunity to inspect the complete company record, source attribution, activity history and commercial stage.</p></div>${summaryMetrics()}${kanban()}`}
function leads(){const rows=data.opps.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return `<div class="section-head"><div><div class="label">LEAD DATABASE</div><h2>Companies & opportunities</h2></div><p>One company can hold multiple opportunities. Duplicates are consolidated against the CRM company identity.</p></div><section class="panel"><div class="panel-head"><h3>CRM Records</h3><span>${rows.length} OPPORTUNITIES</span></div><div class="table-wrap"><table><thead><tr><th>Company</th><th>Source</th><th>Stage</th><th>Location</th><th>Energy Profile</th><th>Friday</th><th>Updated</th></tr></thead><tbody>${rows.map(o=>`<tr data-opp="${esc(o.id)}"><td><b>${esc(o.company?.name||o.title)}</b><small>${esc(o.company?.website||'')}</small></td><td>${esc(o.source||'Other')}</td><td><span class="tag ${o.stage==='WON'?'good':o.stage==='REJECTED'?'bad':''}">${esc(stageLabel(o.stage))}</span></td><td>${esc(o.company?.primaryAddress||o.site?.address||'—')}</td><td>${o.estimatedKwhMin?`${fmt(o.estimatedKwhMin)}–${fmt(o.estimatedKwhMax)} kWh`:'—'}<small>${esc(o.usageConfidence||'')}</small></td><td>${esc(o.fridayStatus||'—')}<small>Score ${o.fridayScore??'—'}</small></td><td>${esc(when(o.updatedAt))}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No CRM records.</td></tr>'}</tbody></table></div></section>`}
function agents(){const sys=data.status?.agents||[];const map=Object.fromEntries(data.agents.map(a=>[a.agent,a]));return `<div class="section-head"><div><div class="label">AUTONOMOUS WORKFORCE</div><h2>Agent CRM accountability</h2></div><p>Every agent has controlled CRM permissions. Tony remains the only agent with no direct CRM access.</p></div><div class="agent-grid">${sys.map(a=>{const p=map[a.name]||{};return `<article class="agent-card ${a.name==='Tony'?'protected':''}"><div class="label">${esc(a.role||'AGENT')}</div><h3>${esc(a.name)}</h3><p>${a.name==='Tony'?'Protected external specialist. CRM updates come only through the read-only Tony Observer.':esc(a.currentTask||'Awaiting work')}</p><div class="agent-status"><span>${esc(a.status||'—')}</span><span>${p.activities||0} CRM events</span></div></article>`}).join('')}</div><div class="section-head"><div><div class="label">PERFORMANCE</div><h2>Recorded outputs</h2></div></div><section class="panel"><div class="table-wrap"><table><thead><tr><th>Agent</th><th>CRM activities</th><th>Sourced leads</th><th>Open</th><th>Won</th><th>Emails</th><th>Replies</th><th>Last activity</th></tr></thead><tbody>${data.agents.map(a=>`<tr><td><b>${esc(a.agent)}</b></td><td>${a.activities||0}</td><td>${a.sourcedLeads||0}</td><td>${a.open||0}</td><td>${a.won||0}</td><td>${a.emailsSent||0}</td><td>${a.replies||0}</td><td>${esc(when(a.lastActivityAt))}</td></tr>`).join('')}</tbody></table></div></section>`}
function outreach(){const o=data.status?.outbound||{},p=data.status?.outreach||{};return `<div class="section-head"><div><div class="label">PEPPER + ULTRON</div><h2>Outreach control</h2></div><p>CRM records sent messages and future responses against the originating opportunity.</p></div><div class="grid-3"><section class="panel rows"><div class="panel-head"><h3>Pepper</h3><span>DRAFTING</span></div><div class="row"><span>Drafts</span><b>${p.total||0}</b></div><div class="row"><span>Ultron approved</span><b>${p.approved||0}</b></div><div class="row"><span>Rework / rejected</span><b>${(p.rework||0)+(p.rejected||0)}</b></div><div class="actionbar"><button id="startOutreach" class="primary">Start</button><button id="stopOutreach">Stop</button><button id="runOutreach">Run Once</button></div></section><section class="panel rows"><div class="panel-head"><h3>Outbound</h3><span>CONTROLLED SEND</span></div><div class="row"><span>Engine</span><b>${o.enabled?'ACTIVE':'STOPPED'}</b></div><div class="row"><span>Sent today</span><b>${o.sentToday||0}/${o.dailyLimit||0}</b></div><div class="row"><span>Total sent</span><b>${o.sentTotal||0}</b></div><div class="actionbar"><button id="startOutbound" class="primary">Start</button><button id="stopOutbound">Stop</button><button id="sendOne">Send One</button></div></section><section class="panel rows"><div class="panel-head"><h3>CRM Outreach</h3><span>MEASUREMENT</span></div><div class="row"><span>Recorded emails</span><b>${data.agents.find(a=>a.agent==='Pepper')?.emailsSent||0}</b></div><div class="row"><span>Recorded replies</span><b>${data.agents.find(a=>a.agent==='Pepper')?.replies||0}</b></div><div class="row"><span>Do not contact</span><b>${o.dncCount||0}</b></div></section></div><div class="section-head"><div><div class="label">DRAFTS</div><h2>Recent work</h2></div></div><section class="panel"><div class="table-wrap"><table><thead><tr><th>Company</th><th>Recipient</th><th>Subject</th><th>Status</th></tr></thead><tbody>${data.drafts.slice(0,80).map(d=>`<tr><td><b>${esc(d.companyName||'')}</b></td><td>${esc(d.recipientEmail||'—')}</td><td>${esc(d.subject||'—')}</td><td>${esc(d.status||'—')}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No drafts.</td></tr>'}</tbody></table></div></section>`}
function operations(){const s=data.status||{},m=s.monitoring||{},t=s.tonyObserver||{};return `<div class="section-head"><div><div class="label">OPERATIONS</div><h2>Aura OS controls</h2></div><p>Existing production controls remain available while CRM becomes the company-wide reporting layer.</p></div><div class="grid-3"><section class="panel rows"><div class="panel-head"><h3>Lead Research</h3><span>VISION · PETER · MJ</span></div><div class="row"><span>Cycle</span><b>${s.leadCycle?.enabled?'ACTIVE':'STOPPED'}</b></div><div class="row"><span>Discovered</span><b>${s.pipeline?.discovered||0}</b></div><div class="row"><span>Friday approved</span><b>${s.pipeline?.approved||0}</b></div><div class="actionbar"><button id="startCycle" class="primary">Start</button><button id="stopCycle">Stop</button><button id="runCycle">Run Once</button></div></section><section class="panel rows"><div class="panel-head"><h3>Steve + Aura</h3><span>MONITORING</span></div><div class="row"><span>Health</span><b>${esc(m.health||'—')}</b></div><div class="row"><span>Open incidents</span><b>${m.openCount||0}</b></div><div class="row"><span>Last scan</span><b>${esc(when(m.lastScanAt))}</b></div><div class="actionbar"><button id="healthScan" class="primary">Health Scan</button><button id="steveReport">Steve Report</button></div></section><section class="panel dark rows"><div class="panel-head"><h3>Tony Observatory</h3><span>READ ONLY</span></div><div class="row"><span>Status</span><b>${esc(t.status||'—')}</b></div><div class="row"><span>Running</span><b>${t.running?'YES':'NO'}</b></div><div class="row"><span>Completed</span><b>${t.completed?.total||0}</b></div><div class="actionbar"><button id="refreshTony" class="primary">Refresh Observer</button></div></section></div>${activityPanel(35)}`}
function content(){if(view==='pipeline')return pipeline();if(view==='leads')return leads();if(view==='agents')return agents();if(view==='outreach')return outreach();if(view==='operations')return operations();return overview()}
function render(){document.querySelector('#app').innerHTML=`<div class="shell">${top()}<main class="page">${content()}</main></div>`;bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-opp]').forEach(r=>r.onclick=()=>openOpp(r.dataset.opp));
  const post=async(url,body={})=>{try{await j(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load()}catch(e){alert(e.message)}};
  if($('#askAura'))$('#askAura').onclick=async()=>{const text=$('#auraQ').value.trim();if(!text)return;try{const r=await j('/api/aura/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});alert(r.reply||r.speech||'Done.')}catch(e){alert(e.message)}};
  if($('#auraQ'))$('#auraQ').onkeydown=e=>{if(e.key==='Enter')$('#askAura').click()};
  if($('#startCycle'))$('#startCycle').onclick=()=>post('/api/lead-cycle/start');if($('#stopCycle'))$('#stopCycle').onclick=()=>post('/api/lead-cycle/stop');if($('#runCycle'))$('#runCycle').onclick=()=>post('/api/lead-cycle/run-once');
  if($('#startOutreach'))$('#startOutreach').onclick=()=>post('/api/outreach/start');if($('#stopOutreach'))$('#stopOutreach').onclick=()=>post('/api/outreach/stop');if($('#runOutreach'))$('#runOutreach').onclick=()=>post('/api/outreach/run-once');
  if($('#startOutbound'))$('#startOutbound').onclick=()=>post('/api/outbound/start');if($('#stopOutbound'))$('#stopOutbound').onclick=()=>post('/api/outbound/stop');if($('#sendOne'))$('#sendOne').onclick=()=>post('/api/outbound/send-one');
  if($('#healthScan'))$('#healthScan').onclick=()=>post('/api/monitor/scan');if($('#steveReport'))$('#steveReport').onclick=()=>post('/api/monitor/report');if($('#refreshTony'))$('#refreshTony').onclick=()=>post('/api/tony/refresh');
}
async function openOpp(id){try{selected=await j(`/api/crm/opportunities/${encodeURIComponent(id)}`);showModal()}catch(e){alert(e.message)}}
function showModal(){const o=selected;if(!o)return;const stages=data.config.stages.filter(x=>!['WON','LOST'].includes(x));const at=o.attribution||{};const modal=document.createElement('div');modal.className='modal';modal.id='crmModal';modal.innerHTML=`<div class="modal-card"><div class="modal-head"><div><div class="eyebrow">${esc(o.id)}</div><h2>${esc(o.company?.name||o.title)}</h2></div><button class="close" id="closeModal">×</button></div><div class="modal-body"><div class="detail-grid"><div class="detail"><span>Current Stage</span><b>${esc(stageLabel(o.stage))}</b></div><div class="detail"><span>Original Source</span><b>${esc(at.recordedSource||o.source||'Other')}</b></div><div class="detail"><span>Confirmed Source</span><b>${esc(at.confirmedSource||'Not yet confirmed')}</b></div><div class="detail"><span>Address</span><b>${esc(o.company?.primaryAddress||o.site?.address||'—')}</b></div><div class="detail"><span>Energy Estimate</span><b>${o.estimatedKwhMin?`${fmt(o.estimatedKwhMin)}–${fmt(o.estimatedKwhMax)} kWh/month`:'—'}</b></div><div class="detail"><span>Friday</span><b>${esc(o.fridayStatus||'—')} · ${o.fridayScore??'—'}</b></div><div class="detail"><span>Solution</span><b>${esc(o.solution||'—')}</b></div><div class="detail"><span>Proposal</span><b>${esc(o.proposalPath||'Not recorded')}</b></div><div class="detail"><span>Value</span><b>${fmtR(o.estimatedValue)}</b></div></div>${o.stage!=='WON'&&o.stage!=='LOST'?`<div class="form-row"><select id="stageSelect">${stages.map(s=>`<option value="${s}" ${s===o.stage?'selected':''}>${stageLabel(s)}</option>`).join('')}</select><button class="btn dark" id="saveStage">Update Stage</button></div><div class="won-box"><div class="label">OWNER OUTCOME CONTROL</div><p>WON attribution is never awarded automatically. Select the originating source; this owner-verified event will later drive Natasha's promotion system.</p><div class="won-actions"><select id="wonSource">${data.config.sources.map(s=>`<option value="${esc(s)}" ${(at.recordedSource||o.source)===s?'selected':''}>${esc(s)}</option>`).join('')}</select><button class="btn" id="markWon">Mark Won</button><button class="btn alt" id="markLost">Mark Lost</button></div></div>`:''}<div class="section-head"><div><div class="label">AUDIT TRAIL</div><h2>Timeline</h2></div></div><div class="timeline">${(o.activities||[]).map(a=>`<div class="activity-item"><time>${esc(when(a.createdAt))}</time><div><b>${esc(a.actor)} · ${esc(stageLabel(a.type))}</b><p>${esc(a.summary)}</p></div></div>`).join('')||'<div class="empty">No activity.</div>'}</div></div></div>`;document.body.appendChild(modal);$('#closeModal').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};
  if($('#saveStage'))$('#saveStage').onclick=async()=>{try{await j(`/api/crm/opportunities/${encodeURIComponent(o.id)}/stage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'Owner',stage:$('#stageSelect').value,reason:'Manual CRM update'})});modal.remove();await load()}catch(e){alert(e.message)}};
  if($('#markWon'))$('#markWon').onclick=async()=>{const source=$('#wonSource')?.value;if(!source)return;if(!confirm(`Mark ${o.company?.name||o.title} WON and attribute the origin to ${source}?`))return;try{await j(`/api/crm/opportunities/${encodeURIComponent(o.id)}/won`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'Owner',source})});modal.remove();await load()}catch(e){alert(e.message)}};
  if($('#markLost'))$('#markLost').onclick=async()=>{const reason=prompt('Why was this opportunity lost?');if(!reason)return;if(!confirm(`Mark ${o.company?.name||o.title} LOST?`))return;try{await j(`/api/crm/opportunities/${encodeURIComponent(o.id)}/lost`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'Owner',reason})});modal.remove();await load()}catch(e){alert(e.message)}};
}
load().catch(e=>document.querySelector('#app').innerHTML=`<div class="page"><div class="notice"><b>CRM failed to load.</b><br>${esc(e.message)}</div></div>`);const es=new EventSource('/api/stream');es.onmessage=()=>load().catch(()=>{});setInterval(()=>load().catch(()=>{}),10000);
