use_default_settings: true

general:
  debug: false
  instance_name: "Ziya Aura Local Search"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  limiter: false
  image_proxy: false
