import {AGENTS,mayCommand} from './agents.mjs';
import {load,mutate} from './store.mjs';
import {providerStatus} from './providers.mjs';
import crypto from 'node:crypto';
import {migrateRegistryFromLeads} from './lead-registry.mjs';
export function seed(){mutate(db=>{db.meta=db.meta||{};if(db.meta.leadCycleEnabled===undefined)db.meta.leadCycleEnabled=false;migrateRegistryFromLeads(db);for(const a of AGENTS){const prior=db.agents[a.name]||{};db.agents[a.name]={...a,status:prior.status||(a.external?'EXTERNAL':'ONLINE'),currentTask:prior.currentTask||null,lastHeartbeat:prior.lastHeartbeat||new Date().toISOString(),lastError:prior.lastError||null}}});}
export function logEvent(agent,level,eventType,message,data={}){return mutate(db=>{const event={id:crypto.randomUUID(),createdAt:new Date().toISOString(),agent,level,eventType,message,data};db.events.unshift(event);db.events=db.events.slice(0,2000);return event})}
export function command(actor,target,action,payload={}){const allowed=mayCommand(actor,target);const reason=target==='Tony'?'Tony is a protected external system. Aura OS is forbidden from commanding or modifying Tony.':allowed?'Hierarchy permits command.':'Hierarchy forbids command.';mutate(db=>{db.auditLogs.unshift({id:crypto.randomUUID(),createdAt:new Date().toISOString(),actor,action,target,allowed,reason,payload});if(allowed&&db.agents[target]){if(action==='PAUSE')db.agents[target].status='PAUSED';if(action==='RESUME')db.agents[target].status='WAITING';db.agents[target].lastHeartbeat=new Date().toISOString();}});if(allowed)logEvent(actor,'INFO','COMMAND',`${actor} issued ${action} to ${target}`,{target,action});return {allowed,reason}}
export function snapshot(){const db=load();const batches=db.leadBatches||[],leads=db.leads||[];return {agents:Object.values(db.agents).sort((a,b)=>b.authority-a.authority),counts:{tasksQueued:db.tasks.filter(t=>t.status==='QUEUED').length,incidentsOpen:db.incidents.filter(i=>i.status==='OPEN').length,leadsPending:leads.filter(l=>l.fridayStatus==='PENDING').length,draftsReview:db.emailDrafts.filter(d=>d.status==='ULTRON_REVIEW').length},pipeline:{discovered:leads.length,fridayReview:leads.filter(l=>l.fridayStatus==='PENDING').length,approved:leads.filter(l=>l.fridayStatus==='APPROVED').length,rework:leads.filter(l=>['REWORK','REJECTED'].includes(l.fridayStatus)).length,duplicates:leads.filter(l=>l.fridayStatus==='DUPLICATE_IGNORED').length,registrySize:(db.leadRegistry||[]).length,pepperQueue:batches.filter(b=>b.readyForPepper).length,pepperDrafts:db.emailDrafts.length,ultronReview:db.emailDrafts.filter(d=>d.status==='ULTRON_REVIEW').length,pepperRework:db.emailDrafts.filter(d=>d.status==='PEPPER_REWORK').length,ultronRejected:db.emailDrafts.filter(d=>d.status==='ULTRON_REJECTED').length,readyToSend:db.emailDrafts.filter(d=>d.status==='APPROVED').length},research:{providers:providerStatus(),cycleEnabled:!!db.meta?.leadCycleEnabled,lastTickAt:db.meta?.leadCycleLastTickAt||null,batches:batches.slice(0,40).map(b=>({...b,leadCounts:{total:leads.filter(l=>l.batchId===b.id).length,approved:leads.filter(l=>l.batchId===b.id&&l.fridayStatus==='APPROVED').length,rework:leads.filter(l=>l.batchId===b.id&&l.fridayStatus==='REWORK').length,rejected:leads.filter(l=>l.batchId===b.id&&l.fridayStatus==='REJECTED').length,duplicates:leads.filter(l=>l.batchId===b.id&&l.fridayStatus==='DUPLICATE_IGNORED').length}}))},events:db.events.slice(0,120),incidents:db.incidents.slice(0,100),serverTime:new Date().toISOString()}}
